package gp6.gymmanagementapp;

import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame 
{
    // Variable mode in integer is used to determine which role the user choose in the main menu
    private final int mode;
    
    public static Staff superAdmin;
    /**
     * Creates new form AdminLogin
     * @param mode
     */
    public Login(int mode) 
    {
        initComponents();
        this.setVisible(true);
        this.mode = mode;
        
        // Change the text based on the role selected by user
        switch (mode) 
        {
            // For staff
            case 0 -> 
            {
                welcomeText.setText("Staff Login");
                this.setTitle("Staff Login Menu");
            }
            case 1 -> 
            {
                welcomeText.setText("Customer Login");
                this.setTitle("Customer Login Menu");
            }
            case 2 -> 
            {
                welcomeText.setText("Trainer Login");
                this.setTitle("Trainer Login Menu");
            }
            case 3 -> 
            {
                welcomeText.setText("Admin Login");
                this.setTitle("Admin Login Menu");
            }
            default -> { }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uname = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        pass = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        back = new javax.swing.JButton();
        welcomeText = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        uname.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        uname.setText("Username: ");

        pass.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        pass.setText("Password:");

        login.setText("Log in");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        welcomeText.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        welcomeText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeText.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(uname))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username)
                                    .addComponent(password))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(back)
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uname)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back)
                    .addComponent(login))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
         String userValue = username.getText();        
         String passValue = String.valueOf(password.getPassword());

        boolean isLoginSuccess = false;
         
        switch (mode) 
        {
            case 0 -> 
            {
                for (Staff staff : GymManagementApp.staffList)
                    if (userValue.equals(staff.getStaffUsername()) && passValue.equals(staff.getStaffPassword()))
                    {
                        isLoginSuccess = true;
                        StaffMainMenu.loggedInStaff = staff;
                        break;
                    }
            }
            case 1 -> 
            {
                for (Customer customer : GymManagementApp.customerList)
                    if (userValue.equals(customer.getCustomerUsername()) && passValue.equals(customer.getCustomerPassword()))
                    {
                        isLoginSuccess = true;
                        CustomerMainMenu.loggedInCustomer = customer;
                        break;
                    }
            }
            case 2 -> 
            {
                for (Trainer trainer : GymManagementApp.trainerList)
                    if (userValue.equals(trainer.getTrainerUsername()) && passValue.equals(trainer.getTrainerPassword()))
                    {    
                        isLoginSuccess = true;
                        TrainerMainMenu.loggedInTrainer = trainer;
                        break;
                    }
            }
            case 3 ->
            {
                if(userValue.equals(GymManagementApp.adminUsername) && passValue.equals(GymManagementApp.adminPassword))
                {
                    AdminMainMenu.AdminUserN = GymManagementApp.adminUsername;
                    AdminMainMenu.AdminPassW = GymManagementApp.adminPassword;
                    isLoginSuccess = true;
                }
            }
            default -> { }
        }

        if (isLoginSuccess)
        {
             switch (mode) 
             {
                 case 0 -> new StaffMainMenu();
                 case 1 -> new CustomerMainMenu();
                 case 2 -> new TrainerMainMenu();
                 case 3 -> new AdminMainMenu();
                 default -> { }
             }
            
            this.dispose();
        }
        else 
            JOptionPane.showMessageDialog(null,"Wrong username or password");
        
    }//GEN-LAST:event_loginActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new MainMenu();
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    public static javax.swing.JButton login;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel uname;
    public javax.swing.JTextField username;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
